version: '3.7'

services:
  db:
    image: postgres:11.6-alpine
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  app:
    image: rebelsmanager_app_test
    build:
      context: .
      args:
        - ADDITIONAL_PACKAGES=nodejs yarn
        - EXECJS_RUNTIME=Node
        - BUNDLE_WITHOUT=production
        - RAILS_ENV=test
    environment:
      - LOCKBOX_MASTER_KEY=a3db67ad66f9778b0db1c5dc81ef336ca76f302f3883755c97f93a2e55bb9be2
      - REDIS_SIDEKIQ_URL=redis://redis:6379/0
      - REDIS_CABLE_URL=redis://redis:6379/1
      - REDIS_CACHE_URL=redis://redis:6379/2
      - RAILS_ENV=test
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisisnotadrill
      - SECRET_KEY_BASE=we-dont-need-a-secret-here
      - XR_BRANCH_DEFAULT_LANGUAGE=en
      - XR_BRANCH_TIMEZONE=Europe/Brussels
    ports:
      - 3000
    links:
      - db
      - redis

volumes:
  db-data:
